---
- name: Listen for events on a webhook
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
      filters:
      - ansible.eda.insert_hosts_to_meta:
          host_path: "payload.hosts"

  rules:
    - name: Collect information
      condition: event.payload.action == "collect_information"
      action:
        run_playbook:
          name: playbooks/collect_information.yml

    - name: Force fsck
      condition: event.payload.action == "force_fsck"
      action:
        run_playbook:
          name: playbooks/fsck.yml
          extra_vars:
            force: true

    - name: Remove force fsck
      condition: event.payload.action == "remove_force_fsck"
      action:
        run_playbook:
          name: playbooks/fsck.yml
          extra_vars:
            force: false
