---
- name: Listen for events on a webhook
  hosts: all

  sources:
    # - ansible.eda.webhook:
    #     host: 0.0.0.0
    #     port: 5000
    #   filters:
    #   - ansible.eda.insert_hosts_to_meta:
    #       host_path: "payload.hosts"
    - ansible.eda.url_check:
        urls:
          - https://robertdebock.nl
        delay: 20

  rules:
    - name: Collect information
      condition: event.payload.action == "collect_information"
      action:
        # run_playbook:
        #   name: playbooks/collect_information.yml
        run_job_template:
          name: "event-driven-ansible (collect_information)"
          organization: "Default"

    - name: All good
      condition: event.url_check.status == "up"
      action:
        run_job_template:
          name: "event-driven-ansible (all_good)"
          organization: "Default"

    - name: All bad
      condition: event.url_check.status != "up"
      action:
        run_job_template:
          name: "event-driven-ansible (all_bad)"
          organization: "Default"
